from unittest import TestCase

from backend.crs.coordinates_transformer import convert_from_wgs84_to_crs_list
from backend.crs.coordinates_transformer_async import async_convert_from_wgs84_to_crs_list

supported_crs_list = [
    {'epsg': 'EPSG:9451', 'name': 'BI height', 'bbox_south_bound_lat': 49.75, 'bbox_west_bound_lon': -9,
     'bbox_north_bound_lat': 61.01, 'bbox_east_bound_lon': 2.01, 'details': '',
     'area': 'Europe - British Isles - UK and Ireland onshore, UKCS'},
    {'epsg': 'EPSG:4230', 'name': 'ED50', 'bbox_south_bound_lat': 25.71, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 48.61, 'details': '',
     'area': 'Europe - ED50 by country'},
    {'epsg': 'EPSG:3855', 'name': 'EGM2008 height', 'bbox_south_bound_lat': -90,
     'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Zero-height surface resulting from the application of the EGM2008 geoid model to the WGS 84 ellipsoid. Replaces EGM96 height (CRS code 5773).',
     'area': 'World'},
    {'epsg': 'EPSG:4231', 'name': 'ED87', 'bbox_south_bound_lat': 34.88, 'bbox_west_bound_lon': -10.56,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 38, 'details': '', 'area': 'Europe - west'},
    {'epsg': 'EPSG:4668', 'name': 'ED79', 'bbox_south_bound_lat': 34.88, 'bbox_west_bound_lon': -10.56,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 38, 'details': '', 'area': 'Europe - west'},
    {'epsg': 'EPSG:5773', 'name': 'EGM96 height', 'bbox_south_bound_lat': -90,
     'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Zero-height surface resulting from the application of the EGM96 geoid model to the WGS 84 ellipsoid. Replaces EGM84 height (CRS code 5798). Replaced by EGM2008 height (CRS code 3855).',
     'area': 'World'},
    {'epsg': 'EPSG:5798', 'name': 'EGM84 height', 'bbox_south_bound_lat': -90,
     'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Zero-height surface resulting from the application of the EGM84 geoid model to the WGS 84 ellipsoid. Replaced by EGM96 height (CRS code 5773).',
     'area': 'World'},
    {'epsg': 'EPSG:7706', 'name': 'EPSG moving platform example', 'bbox_south_bound_lat': -90,
     'bbox_west_bound_lon': -180, 'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Right-handed local 3D CRS fixed to a moving platform. Other permutations of axis order or positive direction may be encountered for which different CSs should be used.',
     'area': 'To be specified'},
    {'epsg': 'EPSG:7914', 'name': 'ETRF89', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaced by ETRF90 (code 7916).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7915', 'name': 'ETRF89', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaced by ETRF90 (code 7917).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7916', 'name': 'ETRF90', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF89 (code 7914). Replaced by ETRF91 (code 7918).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7917', 'name': 'ETRF90', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF89 (code 7915). Replaced by ETRF91 (code 7919).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7918', 'name': 'ETRF91', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF90 (code 7916). Replaced by ETRF92 (code 7920).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7930', 'name': 'ETRF2000', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF97 (code 7928). On the publication of ETRF2005 (code 8397),  the EUREF Technical Working Group recommended that ETRF2000 be the realization of ETRS89. ETRF2014 (code 8401) is technically superior to all earlier realizations of ETRS89.',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7931', 'name': 'ETRF2000', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF97 (code 7929). On the publication of ETRF2005 (code 8399),  the EUREF Technical Working Group recommended that ETRF2000 be the realization of ETRS89. ETRF2014 (code 8403) is technically superior to all earlier realizations of ETRS89.',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:8377', 'name': 'EPSG example wellbore local horizontal CRS - true north',
     'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180, 'bbox_north_bound_lat': 90,
     'bbox_east_bound_lon': 180,
     'details': 'Horizontal component of wellbore local cubic CRS (CRS code 8820). Local coordinates are (0,0) at well reference point, with n-axis aligned to true north.',
     'area': 'To be specified'},
    {'epsg': 'EPSG:8378', 'name': 'EPSG example wellbore local vertical CRS', 'bbox_south_bound_lat': -90,
     'bbox_west_bound_lon': -180, 'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Vertical component of wellbore cubic CRS (CRS code 8820). Depth is relative to the zero depth point used during wellbore survey (e.g. derrick floor).',
     'area': 'To be specified'},
    {'epsg': 'EPSG:8397', 'name': 'ETRF2005', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'On publication in 2007 of this CRS, the EUREF Technical Working Group recommended that ETRF2000 (EPSG code 7930) remained as the preferred realization of ETRS89. Replaced by ETRF2014 (code 8401).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:8399', 'name': 'ETRF2005', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'On publication in 2007 of this CRS, the EUREF Technical Working Group recommended that ETRF2000 (EPSG code 7931) remained as the preferred realization of ETRS89. Replaced by ETRF2014 (code 8403).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:8401', 'name': 'ETRF2014', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF2005 (code 8397). ETRF2014 is technically superior to ETRF2000 but ETRF2000 and other previous realizations may be preferred for backward compatibility reasons. Differences between ETRF2014 and ETRF2000 can reach 7cm.',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:8403', 'name': 'ETRF2014', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF2005 (code 8399). ETRF2014 is technically superior to ETRF2000 but ETRF2000 and other previous realizations may be preferred for backward compatibility reasons. Differences between ETRF2014 and ETRF2000 can reach 7cm.',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:8820', 'name': 'EPSG example wellbore local cubic CRS - true north',
     'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180, 'bbox_north_bound_lat': 90,
     'bbox_east_bound_lon': 180,
     'details': 'Derived from wellbore measured depth, azimuth and inclination measurements where facility reference direction is true north. Further processing is through the individual horizontal and vertical CRSs (CRS codes 8377 and 8378).',
     'area': 'To be specified'},
    {'epsg': 'EPSG:8821', 'name': 'EPSG example wellbore local cubic CRS - grid north (ft)',
     'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180, 'bbox_north_bound_lat': 90,
     'bbox_east_bound_lon': 180,
     'details': 'Derived from wellbore measured depth, azimuth and inclination measurements where facility reference direction is grid north. Further processing is through the individual horizontal and vertical CRSs (CRS codes 8896 and 8897).',
     'area': 'To be specified'},
    {'epsg': 'EPSG:8896', 'name': 'EPSG example wellbore local horizontal CRS - grid north (ft)',
     'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180, 'bbox_north_bound_lat': 90,
     'bbox_east_bound_lon': 180,
     'details': 'Horizontal component of wellbore local cubic CRS (CRS code 8821). Local coordinates are (0,0) at well reference point, with n-axis aligned to grid north in the projected CRS specified in the wellbore local horizontal datum origin definition.',
     'area': 'To be specified'},
    {'epsg': 'EPSG:8897', 'name': 'EPSG example wellbore local vertical CRS (ft)',
     'bbox_south_bound_lat': -90,
     'bbox_west_bound_lon': -180, 'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Vertical component of wellbore cubic CRS (CRS code 8821). Depth is relative to the zero depth point used during wellbore survey (e.g. derrick floor).',
     'area': 'To be specified'},
    {'epsg': 'EPSG:9059', 'name': 'ETRF89', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaced by ETRF90 (code 9060).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:9060', 'name': 'ETRF90', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF89 (code 9059). Replaced by ETRF91 (code 9061).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:9067', 'name': 'ETRF2000', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF97 (code 9066). On the publication of ETRF2005 (code 9068),  the EUREF Technical Working Group recommended that ETRF2000 be the realization of ETRS89. ETRF2014 (code 9069) is technically superior to all earlier realizations of ETRS89.',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:9068', 'name': 'ETRF2005', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'On publication in 2007 of this CRS, the EUREF Technical Working Group recommended that ETRF2000 (EPSG code 9067) remained as the preferred realization of ETRS89. Replaced by ETRF2014 (code 9069).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:9069', 'name': 'ETRF2014', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF2005 (code 9068). ETRF2014 is technically superior to ETRF2000 but ETRF2000 and other previous realizations may be preferred for backward compatibility reasons. Differences between ETRF2014 and ETRF2000 can reach 7cm.',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:4258', 'name': 'ETRS89', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': "Has been realized through ETRF89, ETRF90, ETRF91, ETRF92, ETRF93, ETRF94, ETRF96, ETRF97, ETRF2000, ETRF2005 and ETRF2014. This 'ensemble' covers any or all of these realizations without distinction.",
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:4936', 'name': 'ETRS89', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': "Has been realized through ETRF89, ETRF90, ETRF91, ETRF92, ETRF93, ETRF94, ETRF96, ETRF97, ETRF2000, ETRF2005 and ETRF2014. This 'ensemble' covers any or all of these realizations without distinction.",
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:4937', 'name': 'ETRS89', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': "Has been realized through ETRF89, ETRF90, ETRF91, ETRF92, ETRF93, ETRF94, ETRF96, ETRF97, ETRF2000, ETRF2005 and ETRF2014. This 'ensemble' covers any or all of these realizations without distinction.",
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7919', 'name': 'ETRF91', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF90 (code 7917). Replaced by ETRF92 (code 7921).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7920', 'name': 'ETRF92', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF91 (code 7918). Replaced by ETRF93 (code 7922).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7921', 'name': 'ETRF92', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF91 (code 7919). Replaced by ETRF93 (code 7923).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7922', 'name': 'ETRF93', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF92 (code 7920). Replaced by ETRF94 (code 7924).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7923', 'name': 'ETRF93', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF92 (code 7921). Replaced by ETRF94 (code 7925).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7924', 'name': 'ETRF94', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF93 (code 7922). Replaced by ETRF96 (code 7926).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7925', 'name': 'ETRF94', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF93 (code 7923). Replaced by ETRF96 (code 7927).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7926', 'name': 'ETRF96', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF94 (code 7924). Replaced by ETRF97 (code 7928).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7927', 'name': 'ETRF96', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF94 (code 7925). Replaced by ETRF97 (code 7929).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7928', 'name': 'ETRF97', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF96 (code 7926). Replaced by ETRF2000 (code 7930).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:7929', 'name': 'ETRF97', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF96 (code 7927). Replaced by ETRF2000 (code 7931).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:9061', 'name': 'ETRF91', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF90 (code 9060). Replaced by ETRF92 (code 9062).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:9062', 'name': 'ETRF92', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF91 (code 9061). Replaced by ETRF93 (code 9063).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:9063', 'name': 'ETRF93', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF92 (code 9062). Replaced by ETRF94 (code 9064).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:9064', 'name': 'ETRF94', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF93 (code 9063). Replaced by ETRF96 (code 9065).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:9065', 'name': 'ETRF96', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF94 (code 9064). Replaced by ETRF97 (code 9066).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:9066', 'name': 'ETRF97', 'bbox_south_bound_lat': 32.88, 'bbox_west_bound_lon': -16.1,
     'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 40.18,
     'details': 'Replaces ETRF96 (code 9065). Replaced by ETRF2000 (code 9067).',
     'area': 'Europe - ETRF by country'},
    {'epsg': 'EPSG:3034', 'name': 'ETRS89-extended / LCC Europe', 'bbox_south_bound_lat': 24.6,
     'bbox_west_bound_lon': -35.58, 'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 44.83,
     'details': 'Use formally limited to ETRS89 area of continental Europe but extended for pan-European analysis at small scales. ETRS89 / UTM used for conformal mapping at scales larger than 1:500,000. ETRS89 / LAEA used for statistical applications at any scale.',
     'area': 'Europe - LCC & LAEA'},
    {'epsg': 'EPSG:3035', 'name': 'ETRS89-extended / LAEA Europe', 'bbox_south_bound_lat': 24.6,
     'bbox_west_bound_lon': -35.58, 'bbox_north_bound_lat': 84.73, 'bbox_east_bound_lon': 44.83,
     'details': 'Use ETRS89 / LCC for conformal mapping at 1:500,000 scale or smaller or ETRS89 / UTM for conformal mapping at scales larger than 1:500,000. Use formally limited to ETRS89 area of continental Europe but extended for pan-European analysis at small scales.',
     'area': 'Europe - LCC & LAEA'},
    {'epsg': 'EPSG:5621', 'name': 'EVRF2007 height', 'bbox_south_bound_lat': 35.95,
     'bbox_west_bound_lon': -9.56,
     'bbox_north_bound_lat': 71.21, 'bbox_east_bound_lon': 31.59,
     'details': 'Uses Normal heights. Replaces EVRF2000 height (CRS code 5730). Replaced by EVRF2019 height (CRS code 9389).',
     'area': 'Europe - EVRF2007'},
    {'epsg': 'EPSG:5730', 'name': 'EVRF2000 height', 'bbox_south_bound_lat': 35.95,
     'bbox_west_bound_lon': -9.56,
     'bbox_north_bound_lat': 71.21, 'bbox_east_bound_lon': 31.59,
     'details': 'Uses Normal heights. Replaced by EVRF2007 height (CRS code 5621). In Austria, orthometric heights used instead - see CRS code 9274.',
     'area': 'Europe - EVRF2000'},
    {'epsg': 'EPSG:7409', 'name': 'ETRS89 + EVRF2000 height', 'bbox_south_bound_lat': 35.95,
     'bbox_west_bound_lon': -9.56, 'bbox_north_bound_lat': 71.21, 'bbox_east_bound_lon': 31.59,
     'details': 'Replaced by ETRS89 + EVRF2007 height (CRS code 7423).', 'area': 'Europe - EVRF2000'},
    {'epsg': 'EPSG:7423', 'name': 'ETRS89 + EVRF2007 height', 'bbox_south_bound_lat': 35.95,
     'bbox_west_bound_lon': -9.56, 'bbox_north_bound_lat': 71.21, 'bbox_east_bound_lon': 31.59,
     'details': 'Replaces ETRS89 + EVRF2000 height (CRS code 7409).', 'area': 'Europe - EVRF2007'},
    {'epsg': 'EPSG:9389', 'name': 'EVRF2019 height', 'bbox_south_bound_lat': 35.95,
     'bbox_west_bound_lon': -9.56,
     'bbox_north_bound_lat': 77.07, 'bbox_east_bound_lon': 69.15,
     'details': 'September 2020 adjustment. Replaces 2019 adjustment and EVRF2007 height (CRS code 5621). Uses Normal heights. Zero-tide solution. See EVRF2019 mean-tide height (CRS code 9390) for solution more appropriate for oceanography and GNSS-related activities.',
     'area': 'Europe - EVRF2019'},
    {'epsg': 'EPSG:9390', 'name': 'EVRF2019 mean-tide height', 'bbox_south_bound_lat': 35.95,
     'bbox_west_bound_lon': -9.56, 'bbox_north_bound_lat': 77.07, 'bbox_east_bound_lon': 69.15,
     'details': 'September 2020 adjustment. Replaces 2019 adjustment. Uses Normal heights. Mean-tide solution. See EVRF2019 height (CRS code 9389) for zero-tide solution more appropriate for gravity-related activities.',
     'area': 'Europe - EVRF2019'},
    {'epsg': 'EPSG:9422', 'name': 'ETRS89 + EVRF2019 height', 'bbox_south_bound_lat': 35.95,
     'bbox_west_bound_lon': -9.56, 'bbox_north_bound_lat': 71.21, 'bbox_east_bound_lon': 31.59,
     'details': 'Replaces ETRS89 + EVRF2007 height (CRS code 7423). See also ETRS89 + EVRF2019 mean-tide height (CRS code 9423).',
     'area': 'Europe - ETRF EVRF2019'},
    {'epsg': 'EPSG:9423', 'name': 'ETRS89 + EVRF2019 mean-tide height', 'bbox_south_bound_lat': 35.95,
     'bbox_west_bound_lon': -9.56, 'bbox_north_bound_lat': 71.21, 'bbox_east_bound_lon': 31.59,
     'details': 'See also ETRS89 + EVRF2019 (CRS code 9422).', 'area': 'Europe - ETRF EVRF2019'},
    {'epsg': 'EPSG:9424', 'name': 'ETRS89 + ODN height', 'bbox_south_bound_lat': 49.93,
     'bbox_west_bound_lon': -7.06, 'bbox_north_bound_lat': 58.71, 'bbox_east_bound_lon': 1.8,
     'details': '',
     'area': 'UK - Great Britain mainland onshore'},
    {'epsg': 'EPSG:9425', 'name': 'ETRS89 + ODN (Offshore) height', 'bbox_south_bound_lat': 49.75,
     'bbox_west_bound_lon': -9, 'bbox_north_bound_lat': 61.01, 'bbox_east_bound_lon': 2.01, 'details': '',
     'area': "UK - offshore 49°45'N to 61°N, 9°W to 2°E"},
    {'epsg': 'EPSG:9452', 'name': 'ETRS89 + BI height', 'bbox_south_bound_lat': 49.75,
     'bbox_west_bound_lon': -9,
     'bbox_north_bound_lat': 61.01, 'bbox_east_bound_lon': 2.01, 'details': '',
     'area': 'Europe - British Isles - UK and Ireland onshore, UKCS'},
    {'epsg': 'EPSG:5872', 'name': 'HAT height', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Not specific to any location or epoch.',
     'area': 'World'},
    {'epsg': 'EPSG:5871', 'name': 'HHWLT height', 'bbox_south_bound_lat': -90,
     'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Not specific to any location or epoch.',
     'area': 'World'},
    {'epsg': 'EPSG:5874', 'name': 'High Water height', 'bbox_south_bound_lat': -90,
     'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Not specific to any location or epoch.',
     'area': 'World'},
    {'epsg': 'EPSG:9007', 'name': 'IGb00', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Adopted by the International GNSS Service (IGS) from 2004-01-11 through 2006-11-04. Replaces IGS00, replaced by IGS05 (CRS codes 9004 and 9010). For all practical purposes IGb00 is equivalent to ITRF2000.',
     'area': 'World'},
    {'epsg': 'EPSG:9008', 'name': 'IGb00', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Adopted by the International GNSS Service (IGS) from 2004-01-11 through 2006-11-04. Replaces IGS00, replaced by IGS05 (CRS codes 9005 and 9011). For all practical purposes IGb00 is equivalent to ITRF2000.',
     'area': 'World'},
    {'epsg': 'EPSG:9009', 'name': 'IGb00', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Adopted by the International GNSS Service (IGS) from 2004-01-11 through 2006-11-04. Replaces IGS00, replaced by IGS05 (CRS codes 9006 and 9012). For all practical purposes IGb00 is equivalent to ITRF2000.',
     'area': 'World'},
    {'epsg': 'EPSG:9015', 'name': 'IGb08', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Adopted by the International GNSS Service (IGS) from 2012-10-07 through 2017-01-28. Replaces IGS08, replaced by IGS14 (CRS codes 6934 and 8227). For all practical purposes IGb08 is equivalent to ITRF2008.',
     'area': 'World'},
    {'epsg': 'EPSG:9016', 'name': 'IGb08', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Adopted by the International GNSS Service (IGS) from 2012-10-07 through 2017-01-28. Replaces IGS08, replaced by IGS14 (CRS codes 9013 and 9018). For all practical purposes IGb08 is equivalent to ITRF2008.',
     'area': 'World'},
    {'epsg': 'EPSG:9017', 'name': 'IGb08', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Adopted by the International GNSS Service (IGS) from 2012-10-07 through 2017-01-28. Replaces IGS08, replaced by IGS14 (CRS codes 9014 and 9019). For all practical purposes IGb08 is equivalent to ITRF2008.',
     'area': 'World'},
    {'epsg': 'EPSG:9378', 'name': 'IGb14', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Used for products from the International GNSS Service (IGS) from 2020-05-17. Replaces IGS14 (code 8227). For most practical purposes IGb14 is equivalent to ITRF2014.',
     'area': 'World (by country)'},
    {'epsg': 'EPSG:9379', 'name': 'IGb14', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Used for products from the International GNSS Service (IGS) from 2020-05-17. Replaces IGS14 (code 9018). For most practical purposes IGb14 is equivalent to ITRF2014.',
     'area': 'World'},
    {'epsg': 'EPSG:9380', 'name': 'IGb14', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Used for products from the International GNSS Service (IGS) from 2020-05-17. Replaces IGS14 (code 9019). For most practical purposes IGb14 is equivalent to ITRF2014.',
     'area': 'World'},
    {'epsg': 'EPSG:5829', 'name': 'Instantaneous Water Level height', 'bbox_south_bound_lat': -90,
     'bbox_west_bound_lon': -180, 'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Height relative to instantaneous water level uncorrected for tide. Not specific to any location or epoch.',
     'area': 'World'},
    {'epsg': 'EPSG:5831', 'name': 'Instantaneous Water Level depth', 'bbox_south_bound_lat': -90,
     'bbox_west_bound_lon': -180, 'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Depth relative to instantaneous water level uncorrected for tide. Not specific to any location or epoch.',
     'area': 'World'},
    {'epsg': 'EPSG:5863', 'name': 'ISLW depth', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Not specific to any location or epoch.',
     'area': 'World'},
    {'epsg': 'EPSG:6934', 'name': 'IGS08', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Used for products from International GNSS Service (IGS) analysis centres from 2011-04-17 through 2012-10-06. Replaces IGS05 (code 9010). Replaced by IGb08 (code 9015). For most practical purposes IGS08 is equivalent to ITRF2008.',
     'area': 'World'},
    {'epsg': 'EPSG:8227', 'name': 'IGS14', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Used for products from the International GNSS Service (IGS) from 2017-01-29 to 2020-05-16. Replaces IGb08 (code 9015), replaced by IGb14 (code 9378). For most practical purposes IGS14 is equivalent to ITRF2014.',
     'area': 'World'},
    {'epsg': 'EPSG:9001', 'name': 'IGS97', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Adopted by the International GNSS Service (IGS) from 2000-06-04 through 2001-12-01. Replaced by IGS00 (CRS code 9004). For all practical purposes IGS97 is equivalent to ITRF97.',
     'area': 'World'},
    {'epsg': 'EPSG:9002', 'name': 'IGS97', 'bbox_south_bound_lat': -90, 'bbox_west_bound_lon': -180,
     'bbox_north_bound_lat': 90, 'bbox_east_bound_lon': 180,
     'details': 'Adopted by the International GNSS Service (IGS) from 2000-06-04 through 2001-12-01. Replaced by IGS00 (CRS code 9005). For all practical purposes IGS97 is equivalent to ITRF97.',
     'area': 'World'}]

inputs_map = [(675.8748444444444, 586.9337629629629), (618.9304, 775.3619668148145),
              (780.481130567901, 838.4604420503704), (1111.7502256790121, 731.2372384948145)]


class Test(TestCase):

    def test_async_convert_from_wgs84_to_crs_list(self):
        converted_crs_list = async_convert_from_wgs84_to_crs_list(inputs_map, supported_crs_list)

        self.assertNotEqual(converted_crs_list, [])

    def test_sync_convert_from_wgs84_to_crs_list(self):
        converted_crs_list = convert_from_wgs84_to_crs_list(inputs_map, supported_crs_list)

        self.assertNotEqual(converted_crs_list, [])
